# This is just the label you will see in the GitHub Actions dashboard.
name: Android CI

# This is the alarm clock. It tells GitHub: "Do not run
# this pipeline unless someone pushes code specifically to the main branch."
on:
  push:
    branches:
      - master
# You are defining a single job named "build".
jobs:
    build:
      name: Build APK
# This is where the magic happens. You are telling GitHub to spin up a brand new,
# empty Linux (Ubuntu) virtual computer in the cloud just for you.
      runs-on: ubuntu-latest
# This is a pre-written script provided by GitHub.
# It securely downloads your entire
# Android project into the blank Ubuntu machine so it can be worked on.
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
# Android apps cannot compile without Java. This tells the machine to
# download and install Java 17 (the temurin distribution, which is a standard,
# open-source version of Java).
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
# This is a tool built by the Gradle team. It configures your Android build system
#  and remembers (caches)
# all your downloaded libraries so that your next pipeline run is much faster.
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3
# A raw Linux command. Linux is highly secure by default and won't let random
#  files run.
# This command grants the machine permission to execute your Gradle wrapper (gradlew).
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build Debug APK
          run: ./gradlew assembleDebug